# Generated by Django 3.0 on 2019-12-16 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cus_id', models.IntegerField()),
                ('customer_no', models.CharField(max_length=100)),
                ('mnemonic', models.CharField(max_length=100)),
                ('short_name', models.CharField(max_length=100)),
                ('name1', models.CharField(max_length=100)),
                ('name2', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=100)),
                ('street', models.CharField(max_length=500)),
                ('id_no', models.CharField(max_length=100)),
                ('dob', models.CharField(max_length=100)),
                ('gender', models.CharField(max_length=100)),
                ('marital_status', models.CharField(max_length=100)),
                ('mobile_no', models.CharField(max_length=100)),
                ('o_date', models.CharField(max_length=100)),
                ('ib_customer_id', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'customer',
            },
        ),
    ]
