# Generated by Django 3.0 on 2019-12-16 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='cus_id',
        ),
        migrations.AddField(
            model_name='customer',
            name='cus_user',
            field=models.CharField(default=12, max_length=100),
            preserve_default=False,
        ),
    ]
