# Generated by Django 3.0 on 2019-12-19 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_account'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='balance',
            field=models.CharField(default=0, max_length=1000),
            preserve_default=False,
        ),
    ]
