# Generated by Django 3.0 on 2019-12-23 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_history'),
    ]

    operations = [
        migrations.AddField(
            model_name='history',
            name='message',
            field=models.CharField(default=1, max_length=1000),
            preserve_default=False,
        ),
    ]
